#-------------------------数据库配置/文件上传配置 TODO -------------------------
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url:
    username:
    password:
    druid:
      max-wait: 60000
      initial-size: 5
      max-active: 30
      min-idle: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#-------------------------mybatis-plus配置-------------------------
mybatis-plus:
  mapper-locations: classpath:/com/zhitengda/mapper/xml/*.xml
  type-aliases-package: com.zhitengda
  global-config:
    banner: false
    db-config:
      id-type: UUID
      table-underline: true
    mapper-registry-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#-------------------------微信配置 TODO -------------------------
weixin:
  # 正式
  app-id:
  app-secret:
  token: langao
  dev-mode: true
  show-sql: true
  url-path: https://api.weixin.qq.com/sns/jscode2session
  template-id: i46EbIqZE-YvvOnaT1eut0iWmot0JcFesUeEAfQytg4
  file-path: f:/uploaded/
  real-name-path: